version: 99.99.0-appv.{build}
clone_depth: 10
init:
- SET

environment:
  matrix:
  # Extension testing
  # Package it up to a VSIX
  - nodejs_version: "8.11.3"
    nodejs_arch: "x64"
    VSCE_TASK: package

matrix:
  fast_finish: true

install:
- ps: |
     if ($ENV:nodejs_version -ne $null) {
       Install-Product node $env:nodejs_version $env:nodejs_arch

       Write-Host "Node Version..."
       & node --version

       Write-Host "Updating npm..."
       & npm install -g npm@4 --silent

       Write-Host "npm Version..."
       & npm --version

       Write-Host "Installing VSCE globally..."
       & npm install -g vsce --silent

       Write-Host "Installing modules..."
       & npm install --silent

       Write-Host "Set the package.json version..."
       & node node_modules\gulp\bin\gulp.js bump --specific $ENV:APPVEYOR_BUILD_VERSION
     }
- ps: |
    choco install puppet-agent -y --no-progress

build_script:
- cmd: npm test --silent
- cmd: IF NOT [%GULP_BUILD_TASK%] == [] node node_modules\gulp\bin\gulp.js %GULP_BUILD_TASK%
- cmd: IF NOT [%VSCE_TASK%] == [] vsce %VSCE_TASK%

test_script:
- cmd: IF NOT [%NPM_TASK%] == [] npm run %NPM_TASK%
- cmd: IF NOT [%GULP_TASK%] == [] node node_modules\gulp\bin\gulp.js %GULP_TASK%

artifacts:
- path: .\*.vsix
